service/carservice/urls.py
from django.urls import path
from . import views

app_name = 'carservice'

urlpatterns = [
    path('', views.index, name='index'),
    path('cars/', views.CarListView.as_view(), name='cars'),
    path('cars/<int:pk>', views.CarDetail.as_view(), name='car-detail'),
    path('orders/', views.RepairOrderView.as_view(), name='order-list'),
    path('services/', views.ServicesView.as_view(), name='service-list'),
    path('orders/<int:pk>', views.OrderDetail.as_view(), name='order-detail'),
    path('create_order/', views.CarRepairOrder.as_view(), name='create-order'),
]

service/service/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('rosetta/', include('rosetta.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('carservice/', include('carservice.urls', namespace='carservice')),
    path('', RedirectView.as_view(url='carservice/', permanent=True)),
)

service/carservice/models.py
from datetime import date, timedelta
from unittest.util import _MAX_LENGTH
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from PIL import Image

# import uuid
# from user_profile.models import UserProfile

# Create your models here.

class CarBrand(models.Model):
    """brand representing a car manufacturer."""
    brand = models.CharField(_('Brand'), max_length=100, help_text='Enter a car manufacturer (e.g. BMW, Ford)')
    model = models.CharField(_('Model'), max_length=100, help_text='Enter a car model (e.g. F10, Focus)')

    class Meta:
        ordering = ['brand']
        verbose_name = _('Car Brand')
        verbose_name_plural = _('Car Brands')

    def __str__(self):
        """String for representing the Model object."""
        return self.brand

class Owner(models.Model):
    first_name = models.CharField(_('Name'), max_length=20, db_index=True, default='')
    last_name = models.CharField(_('Surname'), max_length=20, db_index=True, default='')

    class Meta:
        ordering = ['first_name', 'last_name']
        verbose_name = _('Owner')
        verbose_name_plural = _('Owners')

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class Car(models.Model):
    car_brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE, null=True, verbose_name=_('Car brand'))
    car_owner = models.ForeignKey(Owner, on_delete=models.SET_NULL, null=True)
    # car_issue = models.TextField(max_length=1000, help_text='Enter a brief description of the problem', blank=True, default='')
    vin_codes = models.CharField(_('VIN code'), max_length=17, unique=True, help_text='17 Character')
    num_plate = models.CharField(_('Number Plate'), max_length=6)
            
    class Meta:
        ordering = ['car_brand', 'vin_codes']
        verbose_name = _('Car')
        verbose_name_plural = _('Cars')

    def __str__(self) -> str:
        return f'{self.car_brand}'

class Service(models.Model):
    job_name = models.CharField(_('Job Name'), max_length=50)
    price = models.DecimalField(_('Price'), max_digits=5, decimal_places=2, blank=True, null=True)

    class Meta:
        ordering = ['job_name']
        verbose_name = _('Service')
        verbose_name_plural = _('Services')

    def __str__(self):
        return f'{self.job_name} ({self.price} Eur)'

class RepairOrder(models.Model):
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, null=True, verbose_name=_('Car'))
    price = models.DecimalField(_('price'), max_digits=7, decimal_places=2, blank=True, null=True)
    car_issue = models.TextField(_('Issue'), blank=True, null=True)
    due_back = models.DateField(_('Due back'), null=True, blank=True, db_index=True, default=date.today() + timedelta(days=7))

    LOAN_STATUS = (
        (0, _('New')),
        (10, _('Accepted')),
        (20, _('in Progress')),
        (30, _('Done')),
        (50, _('Returned')),
    )

    status = models.PositiveIntegerField(_('Status'), default=0, choices=LOAN_STATUS)

    class Meta:
        ordering = ['car_issue']
        verbose_name = _('Repair order')
        verbose_name_plural = _('Repair orders')

    @property
    def is_overdue(self):
        if self.status < 50 and self.due_back and self.due_back < date.today():
            return True
        return False        

    def __str__(self):
        return f'{self.car}'

class Order(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True, verbose_name=_('Service'))
    repair_order = models.ForeignKey(RepairOrder, on_delete=models.CASCADE, null=True, verbose_name=_('Repair Order'), related_name='order')
    quantity = models.IntegerField(_('Quantity'))
    price = models.DecimalField(_('Price'), max_digits=5, decimal_places=2, blank=True, null=True)

    class Meta:
        ordering = ['repair_order']
        verbose_name = _('Repair job')
        verbose_name_plural = _('Repair jobs') 

    @property
    def repair_price(self):
        return self.quantity * self.price    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.repair_order.price = 0
        for line in self.repair_order.order.all():
            self.repair_order.price += line.repair_price
        self.repair_order.save()

    def __str__(self):
        return f'{self.service} {self.price}'


# test
# test2
# asdasdadasd

service/carservice/forms.py
from django import forms
from .models import RepairOrder, Car

class OrderForm(forms.ModelForm):

    class Meta:
        model = RepairOrder
        fields = ('car', 'car_issue', 'due_back')
        widgets = {
            'car': forms.Select(),
            'car_issue': forms.Textarea(attrs={'class': 'form-control'}),
            'due_back': forms.DateInput(),
        }

# test
# test2
# asdasdadasd

service/carservice/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.conf import settings
from .models import Car, RepairOrder, Service, Owner
from .forms import OrderForm

# Create your views here.

def index(request):
    num_cars = Car.objects.count()
    num_repair_orders = RepairOrder.objects.count()
    num_services = Service.objects.count()
    num_visits = int(request.session.get('num_visits', 0)) + 1
    request.session['num_visits'] = num_visits

    context = {
        'num_cars': num_cars,
        'num_repair_orders': num_repair_orders,
        'num_services': num_services,
        'num_visits': num_visits,

    }
    return render(request, 'carservice/index.html', context=context)

class CarListView(generic.ListView):
    model = Car
    template_name = 'carservice/car_list.html'
    context_object_name = 'cars'
    queryset = Car.objects.all()
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'debug': settings.TIME_ZONE})
        return context

class CarDetail(generic.DetailView):
    model = Car
    template_name = 'carservice/car_detail.html'
    context_object_name = 'car'

class RepairOrderView(generic.ListView):
    model = RepairOrder
    template_name = 'carservice/order_list.html'
    context_object_name = 'orders'
    queryset = RepairOrder.objects.all()
    paginate_by = 5
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'debug': settings.TIME_ZONE})
        return context 
    
class ServicesView(generic.ListView):
    model = Service
    template_name = 'carservice/service_list.html'
    context_object_name = 'services'
    queryset = Service.objects.all()
    paginate_by = 5
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'debug': settings.TIME_ZONE})
        return context

class OrderDetail(generic.DetailView):
    model = RepairOrder
    template_name = 'carservice/order_detail.html'
    context_object_name = 'order'

class CarRepairOrder(generic.CreateView):
    model = RepairOrder
    # fields = ['car', 'description']
    success_url = reverse_lazy('carservice:cars')
    template_name = 'carservice/create_order.html'
    form_class = OrderForm

class Owner(generic.DetailView):
    model = Owner
    template_name = 'carservice/order_detail.html'
    queryset = Service.objects.all()
    context_object_name = 'owner'

service/carservice/templates/carservice/base.html
<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load i18n %}
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <title>{% block title %}{% trans 'Carservise' %}{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
        {% block navigation %}
        <ul class="navbar-nav">
            
                <li class="nav-item"><a class="nav-link" href="{% url 'carservice:index' %}">{% trans 'Home' %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'carservice:cars' %}">{% trans 'Automobiles' %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'carservice:order-list' %}">{% trans 'Orders' %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'carservice:service-list' %}">{% trans 'Services' %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'carservice:create-order' %}">{% trans 'Create order' %}</a></li>
            </li>
        </ul>
        {% endblock navigation %}
        </div>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock content %}

    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

service/carservice/templates/carservice/car_detail.html
{% extends 'carservice/base.html' %}
{% load i18n static %}
{% block content %}
    <h1>{% trans 'Automobile details' %}</h1>
    {% if car.car_brand %}
        <div class="container">
            <br/><br/>
            <table class="table table-hover">
                <thead class="thead-light">
                    <th scope="col">{% trans 'Owner' %}</th>
                    <th scope="col">{% trans 'Car' %}</th>
                    <th scope="col">{% trans 'Number Plate' %}</th>
                    <th scope="col">{% trans 'VIN code' %}</th>
                    <th scope="col">{% trans 'Car Issue' %}</th>
                </thead>
                    <tbody>
                        <tr>
                            <td>{{ car.car_owner  }}</td>
                            <td>{{ car.car_brand }}</td>
                            <td>{{ car.num_plate }}</td>
                            <td>{{ car.vin_codes }}</td>
                            <td>{{ car.car_issue|safe }}</td>
                        </tr>
                    </tbody>
            </table>
        </div>
    {% else %}
        <p>{% trans 'There are no cars in list right now.' %}</p>
    {% endif %}
        
{% endblock content %}

service/carservice/templates/carservice/car_list.html
{% extends 'carservice/base.html' %}
{% load i18n static %}
{% block content %}
    <h1>{% trans 'Automobile list' %}</h1>
    {% if cars %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">{% trans 'first' %}</a>
                    <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
                {% endif %}
                <span class="current">{{ page_obj.number }} {% trans 'of ' %} {{ page_obj.paginator.num_pages }}</span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">{% trans 'next' %}</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{% trans 'last' %} </a>
                {% endif %}
            </span>
        </div>
        <div class="container">
            <br/><br/>
            <table class="table table-hover">
                <thead class="thead-light">
                    <th scope="col">{% trans 'Brand' %}</th>
                    <th scope="col">{% trans 'Number Plate' %}</th>
                    <th scope="col">{% trans 'VIN code' %}</th>
                </thead>
                {% for car in cars %}
                    <tbody>
                        <tr onclick=window.location.href="{% url 'carservice:car-detail' car.id %}">
                            <td>{{ car.car_brand }}</td>
                            <td>{{ car.num_plate }}</td>
                            <td>{{ car.vin_codes }}</td>
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
    {% else %}
    <p>{% trans 'There are cars in service.' %}</p>
    {% endif %}
{% endblock content %}

service/carservice/templates/carservice/create_order.html
{% extends 'carservice/base.html' %}
{% load i18n crispy_forms_tags %}
{% block content %}
<h1>{% trans 'Automobile service registration' %}</h1>
<br>

<div class="content-section">
    <form method="post" action="">
        <fieldset class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-secondary">{% trans 'Confirm' %}</button>
        </div>
    </form>
</div>

{% endblock content %}

service/carservice/templates/carservice/index.html
{% extends 'carservice/base.html' %}
{% load i18n %}

{% block content %}
<section>
    <br>
    <ul class="list-group">
        <li class="list-group-item">{% trans 'Total Cars Registered' %}: {{ num_cars }}</li>
        <li class="list-group-item">{% trans 'Total Orders Created' %}: {{ num_repair_orders }}</li>
        <li class="list-group-item">{% trans 'Total Available Services' %}: {{ num_services }}</li>
        <li class="list-group-item">{% trans 'Number of Your Visits' %}: {{ num_visits }}</li>


    </ul>
</section>

{% endblock content %}

service/carservice/templates/carservice/order_detail.html
{% extends 'carservice/base.html' %}
{% load i18n static crispy_forms_tags %}
{% block content %}
    <h1>{% trans 'Order detail' %}</h1>
    {% if order.car %}
    <br>
    <h4>{% trans 'Car under repair' %}: <strong>{{ order.car }}  {{ order.car.num_plate }}</strong></h4>
    <h5>{% trans 'Car owner' %}: <strong>{{ order.car.car_owner  }}</strong></h5>
    <br/>
        <div class="container">  
            <table class="table table-hover">
                <thead class="thead-light">
                    <th scope="col">{% trans 'Issue' %}</th>
                    <th scope="col">{% trans 'Price' %}</th>
                </thead>               
                <tbody>
                    <tr>
                        <td>{{ order.car_issue }}</td>
                        <td>{{ order.price }}</td>
                    </tr>
                </tbody>   
            </table>
            <h4 align="right">{% trans 'Total price' %}: <strong>{{ order.sum }}</strong></h4>
        </div>
    {% else %}
    <p>{% trans "Automobile does't have any services." %}</p>
    {% endif %}
    <br>
    <hr>

{% endblock content %}

service/carservice/templates/carservice/order_list.html
{% extends 'carservice/base.html' %}
{% load i18n static %}
{% block content %}
    <h1>{% trans 'Orders list' %}</h1>
    {% if orders %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">{% trans 'first' %}</a>
                    <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
                {% endif %}
                <span class="current">{{ page_obj.number }} {% trans 'of ' %} {{ page_obj.paginator.num_pages }}</span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">{% trans 'next' %}</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{% trans 'last' %} </a>
                {% endif %}
            </span>
        </div>
        <div class="container">
            <br/><br/>
            <table class="table table-hover">
                <thead class="thead-light">
                    <th scope="col">{% trans 'Owner' %}</th>
                    <th scope="col">{% trans 'Created at' %}</th>
                    <th scope="col">{% trans 'Car' %}</th>
                    <th scope="col">{% trans 'Issue' %}</th>
                    <th scope="col">{% trans 'Repair status' %}</th>
                    <th scope="col">{% trans 'Due back' %}</th>
                </thead>
                {% for order in orders %}
                    <tbody>
                        <tr onclick=window.location.href="{% url 'carservice:order-detail' order.id %}" class="{% if order.is_overdue %}table-danger{% endif %}">
                            <td>{{ order.car.car_owner }}</td>
                            <td>{{ order.created_at }}</td>
                            <td>{{ order.car }}</td>
                            <td>{{ order.car_issue }}</td>
                            <td>{{ order.get_status_display }}</td>
                            <td>{{ order.due_back }}</td>
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
    {% else %}
    <p>{% trans 'There are no cars in service.' %}</p>
    {% endif %}
{% endblock content %}

service/carservice/templates/carservice/service_list.html
{% extends 'carservice/base.html' %}
{% load i18n static %}
{% block content %}
    <h1>{% trans 'Services list' %}</h1>
    {% if services %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">{% trans 'first' %}</a>
                    <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
                {% endif %}
                <span class="current">{{ page_obj.number }} {% trans 'of ' %} {{ page_obj.paginator.num_pages }}</span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">{% trans 'next' %}</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{% trans 'last' %} </a>
                {% endif %}
            </span>
        </div>
        <div class="container">
            <br/><br/>
            <table class="table table-hover">
                <thead class="thead-light">
                    <th scope="col">{% trans 'Name' %}</th>
                    <th scope="col">{% trans 'Price' %}</th>
                </thead>
                {% for service in services %}
                    <tbody>
                        <tr>
                            <td>{{ service.job_name }}</td>
                            <td>{{ service.price }}</td>
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
    {% else %}
    <p>{% trans 'There are no service yet.' %}</p>
    {% endif %}
{% endblock content %}